/**
 * client-ui-strategies 的 locale 契约：独立 namespace「dshtrading.strategies」
 * （P5 拆包后文案随视图包走，不再寄生 shell 的 dshtrading.market 词典——
 * 同 NS 双包注册会整表覆盖）。key 前缀 sv.*（stage view strategies）。
 */

export type StrategyLocaleKey =
  | 'sv.section.screener'
  | 'sv.section.quant'
  | 'sv.error.noKlines'
  | 'sv.error.failed'
  | 'sv.horizon.short'
  | 'sv.horizon.swing'
  | 'sv.horizon.long'
  | 'sv.symbolLabel'
  | 'sv.intervalDaily'
  | 'sv.run'
  | 'sv.running'
  | 'sv.metrics.totalReturn'
  | 'sv.metrics.cagr'
  | 'sv.metrics.maxDrawdown'
  | 'sv.metrics.sharpe'
  | 'sv.metrics.winRate'
  | 'sv.metrics.profitFactor'
  | 'sv.metrics.tradeCount'
  | 'sv.metrics.tradeUnit'
  | 'sv.metrics.exposure'
  | 'sv.trades.title'
  | 'sv.trades.empty'
  | 'sv.trades.entryTime'
  | 'sv.trades.exitTime'
  | 'sv.trades.entryPrice'
  | 'sv.trades.exitPrice'
  | 'sv.trades.holdingBars'
  | 'sv.trades.netReturn'
  | 'sv.trades.exitReason'
  | 'sv.empty.hint'
  | 'sv.screener.run'
  | 'sv.screener.stop'
  | 'sv.screener.scanLimit'
  | 'sv.screener.universePrefix'
  | 'sv.screener.scanned'
  | 'sv.screener.hits'
  | 'sv.screener.failed'
  | 'sv.screener.noUniverse'
  | 'sv.screener.noHits'
  | 'sv.screener.scanning'
  | 'sv.screener.emptyHint'
  | 'sv.screener.col.symbol'
  | 'sv.screener.col.name'
  | 'sv.screener.col.price'
  | 'sv.screener.col.reason'
  | 'sv.author.failed'
  | 'strat.donchian-breakout'
  | 'strat.donchian-breakout.summary'
  | 'strat.donchian-breakout.param.lookbackEntry'
  | 'strat.donchian-breakout.param.lookbackExit'
  | 'strat.donchian-breakout.reason.entry'
  | 'strat.donchian-breakout.reason.exit'
  | 'strat.rsi-reversion'
  | 'strat.rsi-reversion.summary'
  | 'strat.rsi-reversion.param.rsiPeriod'
  | 'strat.rsi-reversion.param.entryThreshold'
  | 'strat.rsi-reversion.param.exitThreshold'
  | 'strat.rsi-reversion.reason.entry'
  | 'strat.rsi-reversion.reason.exit'
  | 'strat.ema-crossover'
  | 'strat.ema-crossover.summary'
  | 'strat.ema-crossover.param.fastPeriod'
  | 'strat.ema-crossover.param.slowPeriod'
  | 'strat.ema-crossover.reason.entry'
  | 'strat.ema-crossover.reason.exit'
  | 'strat.bollinger-reversion'
  | 'strat.bollinger-reversion.summary'
  | 'strat.bollinger-reversion.param.period'
  | 'strat.bollinger-reversion.param.multiplier'
  | 'strat.bollinger-reversion.reason.entry'
  | 'strat.bollinger-reversion.reason.exit'
  | 'strat.sma-baseline'
  | 'strat.sma-baseline.summary'
  | 'strat.sma-baseline.param.period'
  | 'strat.sma-baseline.reason.entry'
  | 'strat.sma-baseline.reason.exit'
  | 'strat.momentum-12m'
  | 'strat.momentum-12m.summary'
  | 'strat.momentum-12m.param.lookbackBars'
  | 'strat.momentum-12m.reason.entry'
  | 'strat.momentum-12m.reason.exit'
  | 'scr.ma-bull-align'
  | 'scr.ma-bull-align.summary'
  | 'scr.ma-bull-align.param.n1'
  | 'scr.ma-bull-align.param.n2'
  | 'scr.ma-bull-align.param.n3'
  | 'scr.ma-bull-align.col.distLongPct'
  | 'scr.ma-bull-align.reason'
  | 'scr.volume-breakout'
  | 'scr.volume-breakout.summary'
  | 'scr.volume-breakout.param.lookback'
  | 'scr.volume-breakout.param.volMultiple'
  | 'scr.volume-breakout.col.volRatio'
  | 'scr.volume-breakout.col.breakoutPct'
  | 'scr.volume-breakout.reason'
  | 'scr.rsi-oversold'
  | 'scr.rsi-oversold.summary'
  | 'scr.rsi-oversold.param.period'
  | 'scr.rsi-oversold.param.threshold'
  | 'scr.rsi-oversold.col.rsi'
  | 'scr.rsi-oversold.reason'
  | 'scr.near-high'
  | 'scr.near-high.summary'
  | 'scr.near-high.param.window'
  | 'scr.near-high.param.withinPct'
  | 'scr.near-high.col.offHighPct'
  | 'scr.near-high.reason'
  | 'scr.above-ma'
  | 'scr.above-ma.summary'
  | 'scr.above-ma.param.period'
  | 'scr.above-ma.param.slopeBars'
  | 'scr.above-ma.col.aboveMaPct'
  | 'scr.above-ma.col.maSlopePct'
  | 'scr.above-ma.reason'
  | 'strat.momentum-12m.cause.momentumNegative'
  | 'strat.momentum-12m.cause.belowBaseline'

declare module '@deepseek-ai/dsh-client-locale/client' {
  interface LocaleNamespaceMap {
    /** 策略视图词典（client-ui-strategies 包私有）。 */
    'dshtrading.strategies': StrategyLocaleKey
  }
}