/**
 * Slot/locale contract imports + augmentations. Type-only: pulls the host
 * SlotMap merges (sidebar/conversation/layout) and the locale namespace map
 * into every program that sees this file, so PropsRuntime<'…'> resolves.
 */
import type {} from '@deepseek-ai/dsh-client-ui-slots'
import type {} from '@deepseek-ai/dsh-client-ui-sidebar/client'
import type {} from '@deepseek-ai/dsh-client-ui-conversation/client'
import type {} from '@deepseek-ai/dsh-client-ui-layout/client'

/** Locale keys of the dshtrading.market namespace. */
export type MarketLocaleKey =
  | 'tab.watch'
  | 'tab.crypto'
  | 'tab.us'
  | 'tab.cn'
  | 'tab.hk'
  | 'sidebar.addPlaceholder'
  | 'sidebar.add'
  | 'sidebar.addMarketHint'
  | 'sidebar.empty'
  | 'sidebar.emptyHint'
  | 'sidebar.loadFailed'
  | 'sidebar.retry'
  | 'sidebar.markets'
  | 'sidebar.fold'
  | 'sidebar.expand'
  | 'header.symbol'
  | 'header.trend'
  | 'header.priceChange'
  | 'row.remove'
  | 'row.select'
  | 'quote.empty'
  | 'quote.emptyHint'
  | 'quote.open'
  | 'quote.high'
  | 'quote.low'
  | 'quote.prevClose'
  | 'quote.volume'
  | 'quote.updated'
  | 'quote.loadFailed'
  | 'quote.noData'
  | 'stage.quote'
  | 'stage.strategy'
  | 'stage.knowledge'
  | 'strategy.horizon.short'
  | 'strategy.horizon.swing'
  | 'strategy.horizon.long'
  | 'strategy.run'
  | 'strategy.running'
  | 'strategy.symbolLabel'
  | 'strategy.intervalDaily'
  | 'strategy.error.noKlines'
  | 'strategy.error.failed'
  | 'strategy.metrics.totalReturn'
  | 'strategy.metrics.cagr'
  | 'strategy.metrics.maxDrawdown'
  | 'strategy.metrics.sharpe'
  | 'strategy.metrics.winRate'
  | 'strategy.metrics.profitFactor'
  | 'strategy.metrics.tradeCount'
  | 'strategy.metrics.tradeUnit'
  | 'strategy.metrics.exposure'
  | 'strategy.trades.title'
  | 'strategy.trades.empty'
  | 'strategy.trades.entryTime'
  | 'strategy.trades.exitTime'
  | 'strategy.trades.entryPrice'
  | 'strategy.trades.exitPrice'
  | 'strategy.trades.holdingBars'
  | 'strategy.trades.netReturn'
  | 'strategy.trades.exitReason'
  | 'strategy.empty.hint'
  | 'knowledge.search.placeholder'
  | 'knowledge.filter.tag'
  | 'knowledge.filter.allTags'
  | 'knowledge.filter.author'
  | 'knowledge.filter.allAuthors'
  | 'knowledge.filter.credibility'
  | 'knowledge.filter.allCredibility'
  | 'knowledge.filter.sourceType'
  | 'knowledge.filter.allSourceTypes'
  | 'knowledge.filter.reset'
  | 'knowledge.credibility.high'
  | 'knowledge.credibility.medium'
  | 'knowledge.credibility.low'
  | 'knowledge.sourceType.bilibili'
  | 'knowledge.sourceType.wechat'
  | 'knowledge.sourceType.manual'
  | 'knowledge.empty.hint'
  | 'knowledge.empty.filtered'
  | 'knowledge.stats.cards'
  | 'knowledge.stats.clusters'
  | 'knowledge.drawer.title'
  | 'knowledge.drawer.coreClaims'
  | 'knowledge.drawer.factCheck'
  | 'knowledge.drawer.verified'
  | 'knowledge.drawer.discrepancies'
  | 'knowledge.drawer.unverifiable'
  | 'knowledge.drawer.takeaways'
  | 'knowledge.drawer.boundaries'
  | 'knowledge.drawer.tickers'
  | 'knowledge.drawer.related'
  | 'knowledge.drawer.openSource'
  | 'knowledge.drawer.publishedAt'
  | 'knowledge.drawer.author'
  | 'indicator.picker'
  | 'indicator.group.main'
  | 'indicator.group.sub'
  | 'indicator.empty'
  | 'indicator.params'
  | 'indicator.apply'
  | 'indicator.cancel'
  | 'interval.1m'
  | 'interval.3m'
  | 'interval.5m'
  | 'interval.10m'
  | 'interval.15m'
  | 'interval.30m'
  | 'interval.1h'
  | 'interval.4h'
  | 'interval.1d'
  | 'interval.1w'
  | 'interval.1M'
  | 'status.trading'
  | 'status.closed'
  | 'status.midday'
  | 'status.preMarket'
  | 'status.afterHours'
  | 'status.auction'
  | 'browser.history'
  | 'browser.historyEmpty'
  | 'entry.new'
  | 'entry.settings'
  | 'chat.fold'
  | 'chat.expand'

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    /** Trading shell (sidebar browser, quote stage, side panel) copy. */
    'dshtrading.market': MarketLocaleKey
  }
}
