/**
 * Slot/locale contract imports + augmentations. Type-only: pulls the host
 * SlotMap merges (sidebar/conversation/layout) and the locale namespace map
 * into every program that sees this file, so PropsRuntime<'…'> resolves.
 */
import type {} from '@deepseek-ai/dsh-client-ui-slots'
import type {} from '@deepseek-ai/dsh-client-ui-sidebar/client'
import type {} from '@deepseek-ai/dsh-client-ui-conversation/client'
import type {} from '@deepseek-ai/dsh-client-ui-layout/client'

/** Locale keys of the dshtrading.market namespace. */
export type MarketLocaleKey =
  | 'tab.watch'
  | 'tab.crypto'
  | 'tab.us'
  | 'tab.cn'
  | 'tab.hk'
  | 'sidebar.addPlaceholder'
  | 'sidebar.add'
  | 'sidebar.addMarketHint'
  | 'sidebar.empty'
  | 'sidebar.emptyHint'
  | 'sidebar.loadFailed'
  | 'sidebar.retry'
  | 'sidebar.markets'
  | 'sidebar.fold'
  | 'sidebar.expand'
  | 'header.symbol'
  | 'header.trend'
  | 'header.priceChange'
  | 'row.remove'
  | 'row.select'
  | 'quote.empty'
  | 'quote.emptyHint'
  | 'quote.open'
  | 'quote.high'
  | 'quote.low'
  | 'quote.prevClose'
  | 'quote.volume'
  | 'quote.updated'
  | 'quote.loadFailed'
  | 'quote.noData'
  | 'quote.sendToAgent'
  | 'quote.sendToAgentHint'
  | 'quote.sendSending'
  | 'quote.sendSent'
  | 'quote.sendFailed'
  | 'quote.tab.chart'
  | 'quote.tab.fundamentals'
  | 'fundamentals.peTtm'
  | 'fundamentals.peDynamic'
  | 'fundamentals.pb'
  | 'fundamentals.marketCap'
  | 'fundamentals.floatMarketCap'
  | 'fundamentals.turnoverRate'
  | 'fundamentals.dividendYield'
  | 'fundamentals.fiftyTwoWeekHigh'
  | 'fundamentals.fiftyTwoWeekLow'
  | 'fundamentals.unavailable'
  | 'fundamentals.source'
  | 'fundamentals.unit.cn'
  | 'fundamentals.unit.us'
  | 'fundamentals.unit.hk'
  | 'fundamentals.unit.crypto'
  | 'derivatives.title'
  | 'derivatives.oi'
  | 'derivatives.oiValue'
  | 'derivatives.funding'
  | 'derivatives.fundingPositive'
  | 'derivatives.fundingNegative'
  | 'derivatives.longShort'
  | 'derivatives.topLongShort'
  | 'derivatives.taker'
  | 'derivatives.ratioLong'
  | 'derivatives.ratioShort'
  | 'orderbook.title'
  | 'orderbook.close'
  | 'orderbook.unavailable'
  | 'orderbook.buyForce'
  | 'orderbook.sellForce'
  | 'orderbook.spread'
  | 'orderbook.trades'
  | 'orderbook.toggle'
  | 'quote.rangeStats'
  | 'quote.rangeStatsHint'
  | 'range.change'
  | 'range.changeAbs'
  | 'range.high'
  | 'range.low'
  | 'range.amplitude'
  | 'range.volume'
  | 'range.bars'
  | 'range.upDays'
  | 'range.downDays'
  | 'range.closePanel'
  | 'stage.quote'
  | 'stage.strategy'
  | 'stage.knowledge'
  | 'indicator.picker'
  | 'indicator.group.main'
  | 'indicator.group.sub'
  | 'indicator.empty'
  | 'indicator.params'
  | 'indicator.apply'
  | 'indicator.cancel'
  | 'indicator.delete'
  | 'indicator.deleteConfirm'
  | 'interval.1m'
  | 'interval.3m'
  | 'interval.5m'
  | 'interval.10m'
  | 'interval.15m'
  | 'interval.30m'
  | 'interval.1h'
  | 'interval.4h'
  | 'interval.1d'
  | 'interval.1w'
  | 'interval.1M'
  | 'status.trading'
  | 'status.closed'
  | 'status.midday'
  | 'status.preMarket'
  | 'status.afterHours'
  | 'status.auction'
  | 'browser.history'
  | 'browser.historyEmpty'
  | 'browser.showMore'
  | 'browser.showLess'
  | 'entry.new'
  | 'entry.settings'
  | 'chat.fold'
  | 'chat.expand'
  | 'chat.resize'

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    /** Trading shell (sidebar browser, quote stage, side panel) copy. */
    'dshtrading.market': MarketLocaleKey
  }
}
