/**
 * Slot/locale contract imports + augmentations. Type-only: pulls the host
 * SlotMap merges (sidebar/conversation/layout) and the locale namespace map
 * into every program that sees this file, so PropsRuntime<'…'> resolves.
 */
import type {} from '@deepseek-ai/dsh-client-ui-slots'
import type {} from '@deepseek-ai/dsh-client-ui-sidebar/client'
import type {} from '@deepseek-ai/dsh-client-ui-conversation/client'
import type {} from '@deepseek-ai/dsh-client-ui-layout/client'

/** Locale keys of the dshtrading.market namespace. */
export type MarketLocaleKey =
  | 'tab.watch'
  | 'tab.crypto'
  | 'tab.us'
  | 'tab.cn'
  | 'tab.hk'
  | 'sidebar.addPlaceholder'
  | 'sidebar.add'
  | 'sidebar.addMarketHint'
  | 'sidebar.empty'
  | 'sidebar.emptyHint'
  | 'sidebar.loadFailed'
  | 'sidebar.retry'
  | 'sidebar.markets'
  | 'sidebar.fold'
  | 'sidebar.expand'
  | 'header.symbol'
  | 'header.trend'
  | 'header.priceChange'
  | 'row.remove'
  | 'row.select'
  | 'quote.empty'
  | 'quote.emptyHint'
  | 'quote.open'
  | 'quote.high'
  | 'quote.low'
  | 'quote.prevClose'
  | 'quote.volume'
  | 'quote.updated'
  | 'quote.loadFailed'
  | 'quote.noData'
  | 'stage.quote'
  | 'stage.strategy'
  | 'strategy.horizon.short'
  | 'strategy.horizon.swing'
  | 'strategy.horizon.long'
  | 'indicator.picker'
  | 'indicator.group.main'
  | 'indicator.group.sub'
  | 'indicator.empty'
  | 'indicator.params'
  | 'indicator.apply'
  | 'indicator.cancel'
  | 'interval.1m'
  | 'interval.3m'
  | 'interval.5m'
  | 'interval.10m'
  | 'interval.15m'
  | 'interval.30m'
  | 'interval.1h'
  | 'interval.4h'
  | 'interval.1d'
  | 'interval.1w'
  | 'interval.1M'
  | 'status.trading'
  | 'status.closed'
  | 'browser.history'
  | 'browser.historyEmpty'
  | 'entry.new'
  | 'entry.settings'
  | 'chat.fold'
  | 'chat.expand'

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    /** Trading shell (sidebar browser, quote stage, side panel) copy. */
    'dshtrading.market': MarketLocaleKey
  }
}
